#!/bin/bash

### Run COMOPT test and check results

function usage()
{
    echo "Run test and check results"
    echo ""
    echo "./comopt_test.sh"
    echo "-h             -- display this help"
    echo "-e             -- test executable full path"
    echo "-c             -- comparison tool executable full path"
    echo "-r             -- results filenames list"
    echo "-i             -- input directory containing reference results files"
    echo "-t             -- tolerance to compare values of results and reference files"
    echo ""
}

# Default values
COMOPT_EXECUTABLE=
COMOPT_COMPARISON_EXECUTABLE=
COMOPT_RESULTS_FILES=
COMOPT_INPUT_DIRECTORY=""
TOLERANCE=0.001

# Parse arguments of this script
if [ $# -lt 2 ]; then
    usage; exit 1;
fi
while getopts ":e:c:r:i:t:" opt
do
    case $opt in
        e ) COMOPT_EXECUTABLE=$OPTARG;;
        c ) COMOPT_COMPARISON_EXECUTABLE=$OPTARG;;
        r ) COMOPT_RESULTS_FILES=$OPTARG;;
        i ) COMOPT_INPUT_DIRECTORY=$OPTARG;;
        t ) TOLERANCE=$OPTARG;;
        * ) usage; exit 1;;
    esac
done

# Check if comopt test executable exists
COMOPT_EXECUTABLE_FULL_PATH=$(command -v $COMOPT_EXECUTABLE)
if [ ! -x "$COMOPT_EXECUTABLE_FULL_PATH" ]; then
    printf "COMOPT executable $COMOPT_EXECUTABLE does not exist \n"
    exit 1
fi

# Ouput files generated by this script
log_file="test.log"
diffnum_error_file="diffnum.err"
job_log_files="test_has_*"

# Clean
rm -f $log_file $diffnum_error_file $job_log_files

# Command
printf "Launch test : $COMOPT_EXECUTABLE\n"
($COMOPT_EXECUTABLE 2>&1 | tee $log_file) && (touch "test_has_succeeded") || (touch "test_has_failed")

# Refresh output directory
ls > /dev/null

# Initializing of test (comparison between results and reference files)
test=succeed

if [ -f "test_has_failed" ]; then
    test=failed
    printf "Error during execution (check test.log)"
elif [ "$COMOPT_COMPARISON_EXECUTABLE" != "" ]; then
    for RESULT_FILE in $COMOPT_RESULTS_FILES
    do
	RESULT_FILE=${RESULT_FILE//\"}
	RESULT="$RESULT_FILE"
	if [ -f "$RESULT" ]; then
	    RESULT_PATH=./$RESULT_FILE
	    RESULT_PATH=${RESULT_PATH%/*}
	    if [ "$RESULT_PATH" == "." ]; then
		RESULT_PATH=
	    else
		RESULT_PATH=${RESULT_FILE%/*}/
	    fi
	    REFERENCE_FILE=${RESULT_PATH}Ref_$(basename $RESULT_FILE)
	    REFERENCE="$COMOPT_INPUT_DIRECTORY/$REFERENCE_FILE"

	    printf "Comparison launched : $COMOPT_COMPARISON_EXECUTABLE $RESULT $REFERENCE $TOLERANCE\n"
	    DIFFERENCE=`$COMOPT_COMPARISON_EXECUTABLE $RESULT $REFERENCE $TOLERANCE`

	    if [[ $DIFFERENCE != "" ]]; then
		test=failed
		printf "Difference between $RESULT_FILE and $REFERENCE_FILE :\n$DIFFERENCE" | tee $diffnum_error_file
		break
	    else
		printf "Comparison between $RESULT_FILE and $REFERENCE_FILE => Success\n"
	    fi
	else
	    test=failed
	    printf "Error during execution. (result file $RESULT_FILE not created)" | tee $diffnum_error_file
	    break
	fi
    done
fi

if [ "$test" = succeed ]; then
# Test succeed
    exit 0
else
# Test failed
    exit 1
fi
