name: COMOPT CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add submodules
      run: git submodule init
    - name: Update submodule
      run: git submodule update 
    - uses: actions/checkout@v3
    - name: build
      run: ./build.sh build
    - name: test
      run: ./build.sh test
