name: COMOPT CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add vcpkg
      run: git submodule add https://github.com/microsoft/vcpkg.git
    - name: Update submodule
      run: git submodule update --init --recursive
    - uses: actions/checkout@v3
    - name: build
      run: ./build.sh build
    - name: test
      run: ./build.sh test
