name: COMOPT CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ./build.sh build
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
